# Generated by Django 4.0.5 on 2022-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_otp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
