# Generated by Django 4.0.5 on 2022-06-03 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profiles_id_alter_profiles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
