# Generated by Django 4.0.5 on 2022-06-07 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to='post', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'png', 'gif', 'svg'])]),
        ),
    ]
