# Generated by Django 4.0.5 on 2022-06-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_field_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='fields',
        ),
        migrations.AddField(
            model_name='form',
            name='fields',
            field=models.ManyToManyField(blank=True, null=True, to='user.field'),
        ),
    ]
