# Generated by Django 4.0.5 on 2022-06-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='fields',
            field=models.ManyToManyField(to='user.field'),
        ),
    ]
