# Generated by Django 4.0.5 on 2022-06-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_userdetails_created_at_userdetails_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
